version: '3.4'
services:
    mysql:
        container_name: mysql
        image: mysql:latest
        ports:
            - "3306:3306"
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
            - ./seed.sql:/seed.sql
            - mysql-db:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=mysql
volumes:
    mysql-db: